

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultOFIndAll.java
 *
 * Created on Mar 14, 2012, 8:51:35 PM
 */
/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.BorderFactory.*;

public class ResultOFIndAll extends javax.swing.JFrame {

    private DefaultTableModel model;
    private JTable table;
    private JScrollPane scrollPane;
    private ButtonGroup btg;
    private String s_id = "", nam = "";


    /** Creates new form ResultOFIndAll
     * @param stu_id
     * @param sname
     */
    public ResultOFIndAll(String stu_id, String sname) {
        s_id = stu_id;
        nam = sname;
        
        initComponents();
        id.setText(s_id.toUpperCase());
        name.setText(nam.toUpperCase());
        pnl1.setBorder(BorderFactory.createLineBorder(java.awt.Color.BLACK));
        model = new DefaultTableModel();
        table = new JTable(model);
        table.setFillsViewportHeight(true);
        model.addColumn("S.NO");
        model.addColumn("Grade");
        model.addColumn("Roll No.");
        model.addColumn("Term");
        model.addColumn("Report");
        model.addColumn("Published");
        int h = ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED;
        int v = ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED;
        scrollPane = new JScrollPane(table, v, h);
        pnl1.add(scrollPane);
        scrollPane.setBounds(5, 180, 610, 285);
        btg = new ButtonGroup();
        btg.add(all);
        btg.add(cur);
        all.setSelected(true);
        examReport(2,0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        pnl1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cur = new javax.swing.JRadioButton();
        all = new javax.swing.JRadioButton();

        getContentPane().setLayout(null);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(330, 480, 90, 30);

        btnPrint.setText("Print");
        getContentPane().add(btnPrint);
        btnPrint.setBounds(180, 480, 90, 30);

        pnl1.setLayout(null);

        header.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fee2.png"))); // NOI18N
        pnl1.add(header);
        header.setBounds(10, 0, 600, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("ID. No:");
        pnl1.add(jLabel2);
        jLabel2.setBounds(30, 130, 50, 20);

        id.setFont(new java.awt.Font("Tahoma", 0, 12));
        pnl1.add(id);
        id.setBounds(100, 130, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Name:");
        pnl1.add(jLabel4);
        jLabel4.setBounds(30, 70, 50, 20);

        name.setFont(new java.awt.Font("Tahoma", 0, 12));
        pnl1.add(name);
        name.setBounds(100, 70, 140, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Specify Date"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        cur.setText("Current Year");
        cur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curActionPerformed(evt);
            }
        });
        jPanel1.add(cur);
        cur.setBounds(190, 30, 100, 25);

        all.setText("Till Now");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });
        jPanel1.add(all);
        all.setBounds(60, 30, 70, 25);

        pnl1.add(jPanel1);
        jPanel1.setBounds(270, 70, 330, 90);

        getContentPane().add(pnl1);
        pnl1.setBounds(0, 0, 621, 470);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-637)/2, (screenSize.height-555)/2, 637, 555);
    }// </editor-fold>//GEN-END:initComponents

    private void curActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curActionPerformed
        // TODO add your handling code here:
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
         examReport(1,1);
}//GEN-LAST:event_curActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        // TODO add your handling code here:
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);

        }
        examReport(2,1);
}//GEN-LAST:event_allActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    public void examReport(int status, int option) {
        Student s = new Student();
        String query = null;
        switch (status) {
            case 1:
                query = "SELECT examterm.grade, exam.roll, examterm.term, exam.report, examterm.date FROM exam,examterm WHERE exam.id = examterm.id AND exam.studentId = '" + s_id + "'"
                        + " AND date_format(examterm.date,'%y') = date_format(now(),'%y')";
                break;
            case 2:
                query = "SELECT examterm.grade, exam.roll, examterm.term, exam.report, examterm.date FROM exam,examterm WHERE exam.id = examterm.id AND exam.studentId = '" + s_id + "'";
                break;
        }
        boolean report = s.examFeeIndAllReport("exam",model,query);
        s.Close();
        if(!report){
                if (option != 0) {
                    JOptionPane.showMessageDialog(null, "No data found. \nThank you!!");
                }
            }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                //  new ResultOFIndAll().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton all;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JRadioButton cur;
    private javax.swing.JLabel header;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JPanel pnl1;
    // End of variables declaration//GEN-END:variables
}
