

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentGroupF.java
 *
 * Created on Jan 30, 2012, 12:41:43 PM
 */
/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import java.sql.*;

public class StudentGroupF extends javax.swing.JFrame {

    private Connection con = null;
    private ResultSet rs = null;
    private Statement stm = null;
    private PreparedStatement pstm = null;
    private String query = null;
    private String Driver = "com.mysql.jdbc.Driver";
    private String Url = "jdbc:mysql://localhost:3306/System";
    private int[] statusBit = {1, 2, 3};

    /** Creates new form StudentGroupF */
    public StudentGroupF() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        category = new javax.swing.JComboBox();
        clbl = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        glbl = new javax.swing.JLabel();
        grade = new javax.swing.JComboBox();
        cancel = new javax.swing.JButton();

        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/STUDSEC.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 63);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Student Search"));
        jPanel2.setLayout(null);

        category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "STUDENT", "FEE", "EXAM" }));
        jPanel2.add(category);
        category.setBounds(160, 15, 90, 30);

        clbl.setText("Category:");
        jPanel2.add(clbl);
        clbl.setBounds(80, 20, 60, 20);

        search.setText("Search");
        search.setPreferredSize(new java.awt.Dimension(61, 20));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(460, 15, 90, 30);

        glbl.setText("Class:");
        jPanel2.add(glbl);
        glbl.setBounds(280, 20, 50, 20);

        grade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9", "X10" }));
        jPanel2.add(grade);
        grade.setBounds(340, 15, 90, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 70, 580, 60);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(260, 135, 90, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-616)/2, (screenSize.height-212)/2, 616, 212);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if (category.getSelectedIndex() == 0 || grade.getSelectedIndex() == 0) {
            if (category.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please Select the Category");
            } else {
                JOptionPane.showMessageDialog(this, "Please Select the Grade");
            }
        } else if (category.getSelectedIndex() == 1 || category.getSelectedIndex() == 2) {
            createTableForm((String) category.getSelectedItem(), (String) grade.getSelectedItem(), category.getSelectedIndex());

        } else {
            String input = JOptionPane.showInputDialog(this, "Please Enter the Term Exam.\nAs 1 or 2 or 3");
            if (input.trim().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "You haven't specify the Terms");
            } else {
                createTableForm(input, (String) grade.getSelectedItem(), category.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    protected void createTableForm(String term, String grade, int cases) {
        CommonTabulateData td = new CommonTabulateData();
        String title = "";
        switch (cases) {
            case 1:
                query = "SELECT studentId,name,gardianName,address,contact,grade,enrolled FROM "
                        + "student_info WHERE grade = '" + grade + "'";
                title = "STUDENT'S INFO OF GRADE "+grade;

                break;
            case 2://need to checked out
                query = "SELECT student_info.studentId,student_info.name,student_info.contact,"
                        + "student_info.grade,fee.fstatus FROM student_info,fee WHERE student_info.studentId = fee.studentId "
                        + "AND fee.grade = '" + grade + "' AND date_format(dpay,'%y') = date_format(now(),'%y')";
                title = "FEE PAYMENTS INFO OF GRADE "+grade;
                break;
            case 3:
                query = "SELECT exam.name, exam.studentId, exam.roll, exam.report, exam.contact FROM exam,examterm "
                        + "WHERE exam.id = examterm.id AND examterm.grade = '" + grade + "' AND examterm.term = '" + term + "' AND date_format(date,'%y') = date_format(now(),'%y')";
                title = "RESULTS OF GRADE "+grade+" OF TERM "+ term;
        }
        if (td.dataValidCheck(query)) {
            new TabulateData(title,query).setVisible(true);
            td.Close();
        } else {
            JOptionPane.showMessageDialog(null, "NO data found.\nData has not been loaded to Database. Sorry", "Message", JOptionPane.OK_OPTION);
        }
        td.Close();
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new StudentGroupF().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox category;
    private javax.swing.JLabel clbl;
    private javax.swing.JLabel glbl;
    private javax.swing.JComboBox grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
