

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentSec.java
 *
 * Created on Sep 15, 2011, 11:03:44 PM
 */
/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import java.sql.*;

public class StudentSecF extends javax.swing.JFrame {

    //private Student s = new Student();
    /** Creates new form StudentSec */
    public StudentSecF() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        info = new javax.swing.JButton();
        fee = new javax.swing.JButton();
        result = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Enter Required Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(590, 60));
        jPanel4.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setText("Roll No:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(430, 40, 50, 20);

        roll.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPanel4.add(roll);
        roll.setBounds(490, 30, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setText("Name:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 40, 50, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel9.setText("Grade:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(290, 40, 50, 20);

        name.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPanel4.add(name);
        name.setBounds(70, 30, 200, 30);

        grade.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPanel4.add(grade);
        grade.setBounds(340, 30, 80, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 70, 590, 80);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 51))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(590, 60));
        jPanel5.setLayout(null);

        info.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info.setForeground(new java.awt.Color(51, 0, 204));
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        info.setText("Info");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        jPanel5.add(info);
        info.setBounds(40, 20, 140, 33);

        fee.setFont(new java.awt.Font("Tahoma", 1, 12));
        fee.setForeground(new java.awt.Color(51, 0, 204));
        fee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        fee.setText("Fee ");
        fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeActionPerformed(evt);
            }
        });
        jPanel5.add(fee);
        fee.setBounds(340, 20, 140, 33);

        result.setFont(new java.awt.Font("Tahoma", 1, 12));
        result.setForeground(new java.awt.Color(51, 0, 204));
        result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        result.setText("Exam");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        jPanel5.add(result);
        result.setBounds(190, 20, 140, 33);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(500, 20, 80, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 150, 590, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/STUDSEC.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 590, 63);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-605)/2, (screenSize.height-272)/2, 605, 272);
    }// </editor-fold>//GEN-END:initComponents

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        Student s = new Student();
        String sname = (name.getText()).trim();
        String sgrade = (grade.getText()).trim();
        String sroll = (roll.getText()).trim();
        int iroll = Integer.parseInt(sroll);



        if (sname.length() > 1 && sgrade.length() > 1 && sroll.length() >= 1) {
            String stname = getName(sname);
            if (stname.length() > 1) {
                String query = "SELECT * FROM student_info WHERE name = '"+stname+"' AND grade = '"+sgrade+"' AND roll = '"+iroll+"'";
                //s.Connect();
                ResultSet rs = s.getInfo(query);
                if (rs != null) {
                    new StudentInfoF(rs).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Data not Found");
                    name.setText("");
                    grade.setText("");
                    roll.setText("");
                    s.Close();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Enter the full name !!!!", "Notice", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill up the both field", "Notice", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_infoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeActionPerformed
        // TODO add your handling code here:
        String sname = (name.getText()).trim();
        String sgrade = (grade.getText()).trim();
        String sroll = (roll.getText()).trim();
        String[] student = getId(sname, sgrade, sroll);
        if (!student[1].equalsIgnoreCase("")) {
            if (!student[0].equalsIgnoreCase("")) {
                new FeeOFIndAll(student[0], student[1], sgrade).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Student Record of given name: " + student[1] + " is found..");
            }
        }

    }//GEN-LAST:event_feeActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
        String sname = (name.getText()).trim();
        String sgrade = (grade.getText()).trim();
        String sroll = (roll.getText()).trim();

        String[] student = getId(sname, sgrade, sroll);
        if (!student[1].equalsIgnoreCase("")) {
            if (!student[0].equalsIgnoreCase("")) {
                new ResultOFIndAll(student[0], student[1]).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No Student Record of given name: " + student[1] + " is found..");
            }
        }

    }//GEN-LAST:event_resultActionPerformed

    private String[] getId(String sname, String sgrade, String sroll) {
        //String[] studentid = null;
        Student s = new Student();
        String stname = "";
        String stu_id = "";

        if (sname.length() > 1 && sgrade != null && sroll != null) {
            stname = getName(sname).trim();
            if (stname.length() > 1) {
                //s.Connect();
                stu_id = s.getValidation(stname, sgrade, Integer.parseInt(sroll));
                s.Close();
            } else {
                JOptionPane.showMessageDialog(this, "Enter the full name !!!!", "Notice", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill up the both field", "Notice", JOptionPane.PLAIN_MESSAGE);
        }

        return new String[]{stu_id, stname};

    }

    private String getName(String name) {
        int len1 = 0, len2 = 0, i = 0, j = 0;
        String sname = "", s1 = "", s2 = "", s3 = "", s4 = "";


        i = name.indexOf(" ");
        if (i > 0) {
            len1 = name.length();
            s1 = name.substring(0, i);
            sname += s1 + " ";
            s2 = (name.substring(i, len1)).trim();

            j = s2.indexOf(" ");
            if (j > 0) {
                len2 = s2.length();
                s3 = s2.substring(0, j);
                sname += s3 + " ";
                s4 = (s2.substring(j, len2)).trim();
                sname += s4 + " ";
            } else {
                sname += s2;
            }
        }

        return (sname);
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new StudentSecF().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fee;
    private javax.swing.JTextField grade;
    private javax.swing.JButton info;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField name;
    private javax.swing.JButton result;
    private javax.swing.JTextField roll;
    // End of variables declaration//GEN-END:variables
}
/* code for removing unwanated spaces between names
 *
 *
i = sname.indexOf(" ");
if(i>0){
s1 = sname.substring(0, i);
oname = s1+" ";
s2 = (sname.substring(i, len1)).trim();
len2 = s2.length();
j = s2.indexOf(" ");
if(j>0){
s3 = s2.substring(0, j);
oname += s3+" ";
s4 = (s2.substring(j, len2)).trim();
oname += s4+" ";
}
else
oname += s2;
 */
