package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fee.java
 *
 * Created on Sep 9, 2011, 5:06:08 PM
 */

/**
 *
 * @author kiranroma
 */
import javax.swing.UIManager.*;
import javax.swing.*;
public class Fee extends javax.swing.JPanel {

    /** Creates new form Fee */
    public Fee() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pay = new javax.swing.JButton();
        ok = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(1, 1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/studfeesec.png"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Grade:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 20, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 20, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Student ID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 80, 80, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Roll No:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(450, 20, 50, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(90, 20, 200, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(90, 80, 100, 30);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(510, 20, 70, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(370, 20, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Total Fee:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(310, 80, 70, 30);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(410, 80, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Rs. ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 90, 20, 20);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(597, 40));
        jPanel2.setLayout(null);

        pay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pay.setText("Unpaid");
        pay.setActionCommand("Unpaid");
        jPanel2.add(pay);
        pay.setBounds(130, 10, 90, 25);

        ok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ok.setText("OK");
        jPanel2.add(ok);
        ok.setBounds(370, 10, 90, 25);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton ok;
    private javax.swing.JButton pay;
    // End of variables declaration//GEN-END:variables

//    public static void main(String args[]){
//        try {
//    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//        if ("Nimbus".equals(info.getName())) {
//            UIManager.setLookAndFeel(info.getClassName());
//            break;
//        }
//    }
//} catch (Exception e) {
//    // If Nimbus is not available, you can set the GUI to another look and feel.
//}
//        try{
//       // javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
//        //javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
//        }
//        catch(Exception e){}
//       // UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
//    javax.swing.JFrame jf = new javax.swing.JFrame("fee secs");
//    jf.add(new Fee());
//    jf.setVisible(true);
//    //jf.pack();
//    jf.setSize(600,430);
//    jf.setResizable(false);
//    jf.setDefaultCloseOperation(jf.EXIT_ON_CLOSE);
//    }
}
