package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Mar 14, 2012, 12:50:34 PM
 */

/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Login extends javax.swing.JFrame {

    FrmSplash FormSplash = new FrmSplash();
    Thread ThFormSplash = new Thread(FormSplash);

    /** Creates new form Login */
    public Login() {
        
        initComponents();
        loadSplashScreen();
		//We will dispose now the FormSplash because it is now useless
//        btnlog.registerKeyboardAction(btnlog.getActionForKeyStroke(
//
//                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
//
//                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
//
//                                      JComponent.WHEN_FOCUSED);
//        addKeyListener(new KeyAdapter(){
//            public void keyPressed(KeyEvent ke){
//                //KeyStroke ke;
//                if(ke.getKeyCode() == KeyEvent.VK_ENTER){
//                    LoginCheck();
//                }
//            }
//        });
        FormSplash.dispose();
    }

    protected void loadSplashScreen(){
		//Start the thread
		ThFormSplash.start();
		while(!FormSplash.isShowing()){
			try{
				//Display the FormSplash for 5 seconds
				Thread.sleep(2000);
			}catch(InterruptedException e){
			}
		}
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnllog = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannerFinal.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-2, 0, 440, 60);

        pnllog.setBackground(new java.awt.Color(153, 255, 153));
        pnllog.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/500807.png"))); // NOI18N
        pnllog.add(jLabel2);
        jLabel2.setBounds(10, 10, 130, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calc (1).png"))); // NOI18N
        pnllog.add(jLabel3);
        jLabel3.setBounds(80, 20, 40, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LogIn");
        pnllog.add(jLabel4);
        jLabel4.setBounds(170, 10, 220, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Password:");
        pnllog.add(jLabel5);
        jLabel5.setBounds(160, 80, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("UserName:");
        pnllog.add(jLabel6);
        jLabel6.setBounds(160, 40, 80, 30);
        pnllog.add(txtuser);
        txtuser.setBounds(260, 40, 150, 30);

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        pnllog.add(btncancel);
        btncancel.setBounds(320, 130, 90, 30);

        btnlog.setText("Log In");
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });
        pnllog.add(btnlog);
        btnlog.setBounds(170, 130, 90, 30);

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });
        pnllog.add(txtpass);
        txtpass.setBounds(260, 80, 150, 30);

        getContentPane().add(pnllog);
        pnllog.setBounds(0, 62, 435, 170);

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Copy Right @ NCIT");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(64, 4, 280, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 234, 435, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-452)/2, (screenSize.height-302)/2, 452, 302);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        // TODO add your handling code here:
        LoginCheck();

    }//GEN-LAST:event_btnlogActionPerformed

    public void LoginCheck(){
        String user = txtuser.getText().trim(), pass = txtpass.getText().trim();
        //System.out.println(pass);
        if( user.equalsIgnoreCase("admin") && pass.equalsIgnoreCase("admin")){
            this.dispose();
            new Home().setVisible(true);

        }
        else{
            lblerror = new javax.swing.JLabel();
            lblerror.setForeground(new java.awt.Color(255, 0, 0));
            lblerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblerror.setText("Error! Please Enter correct Username and Password!!");
            pnllog.add(lblerror);
            lblerror.setBounds(135, 110, 300, 20);
        }
    }


    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            LoginCheck();
        }
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        //java.awt.EventQueue.invokeLater(new Runnable() {
         //   public void run() {
        try{
            javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }
        catch(Exception e){

        }
                new Login().setVisible(true);
          //  }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnllog;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel lblerror;
}
