package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewTeacherF.java
 *
 * Created on Jan 24, 2012, 9:01:55 AM
 */
/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import java.io.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.regex.Pattern;

public final class NewTeacherF extends javax.swing.JFrame {

    private String photoPath = null;
    private String query = null;
    private Calendar cl = new GregorianCalendar();
    private int y;
    private String phoneNum = "^9+([87])+([014])(\\d{7})$";

    private String words = "[a-bA-Z\\s]+$";
    //private String add = "[a-bA-Z\\,]+$";

    /** Creates new form NewTeacherF */
    public NewTeacherF() {
        initComponents();
        y = cl.get(Calendar.YEAR);

        comboBoxYearValues(y);
    }

    protected void comboBoxYearValues(int y) {

        cbbdy.addItem("Select");
        cbady.addItem("Select");

        //for birth year

        for (int i = y - 50; i <= y - 18; i++) {
            cbbdy.addItem(String.valueOf(i));
        }

        //for addmission year
        for (int j = y; j >= y - 20; j--) {
            cbady.addItem(String.valueOf(j));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        photo = new javax.swing.JLabel();
        upload = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        qua = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cbbdd = new javax.swing.JComboBox();
        cbbdy = new javax.swing.JComboBox();
        cbbdm = new javax.swing.JComboBox();
        cbady = new javax.swing.JComboBox();
        cbadm = new javax.swing.JComboBox();
        cbadd = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        contact = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        btncancel = new javax.swing.JButton();
        btncon = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TADD.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 699, 65);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "FIll Up The Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Last Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(480, 30, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Gender:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(370, 90, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Middle Name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(250, 30, 90, 20);
        jPanel2.add(lname);
        lname.setBounds(560, 20, 130, 30);
        jPanel2.add(mname);
        mname.setBounds(340, 20, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("First Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 30, 70, 20);
        jPanel2.add(fname);
        fname.setBounds(100, 20, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Date of Birth:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 90, 90, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Employed Date:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 190, 99, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Qualification:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 140, 80, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("Address:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(340, 140, 60, 20);
        jPanel2.add(address);
        address.setBounds(410, 130, 150, 30);

        gender.setFont(new java.awt.Font("Tahoma", 0, 14));
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female" }));
        jPanel2.add(gender);
        gender.setBounds(440, 80, 120, 30);

        photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NO PHOTO.png"))); // NOI18N
        jPanel2.add(photo);
        photo.setBounds(580, 60, 110, 140);

        upload.setFont(new java.awt.Font("Tahoma", 1, 5));
        upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        upload.setText("Upload Image");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jPanel2.add(upload);
        upload.setBounds(580, 205, 110, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("D");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(260, 60, 40, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("M");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(190, 60, 40, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("A.D.");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(340, 190, 30, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("D");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(280, 160, 20, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("M");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(210, 160, 40, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Y");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(130, 160, 50, 20);

        qua.setFont(new java.awt.Font("Tahoma", 0, 14));
        qua.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "GENERAL", "SLC", "BACHELOR", "MASTER", "PH.D" }));
        jPanel2.add(qua);
        qua.setBounds(100, 130, 120, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Y");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(100, 60, 60, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel28.setForeground(new java.awt.Color(51, 51, 255));
        jLabel28.setText("Contact No:");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(380, 190, 75, 20);

        jPanel2.add(cbbdd);
        cbbdd.setBounds(250, 80, 50, 30);

        jPanel2.add(cbbdy);
        cbbdy.setBounds(100, 80, 70, 30);

        cbbdm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        cbbdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbdmActionPerformed(evt);
            }
        });
        jPanel2.add(cbbdm);
        cbbdm.setBounds(180, 80, 60, 30);

        jPanel2.add(cbady);
        cbady.setBounds(120, 180, 70, 30);

        cbadm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        cbadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbadmActionPerformed(evt);
            }
        });
        jPanel2.add(cbadm);
        cbadm.setBounds(200, 180, 60, 30);

        jPanel2.add(cbadd);
        cbadd.setBounds(270, 180, 50, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("A.D.");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(310, 90, 30, 20);

        try {
            contact.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(contact);
        contact.setBounds(460, 180, 115, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 700, 250);

        jPanel3.setPreferredSize(new java.awt.Dimension(699, 45));
        jPanel3.setLayout(null);

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel3.add(btncancel);
        btncancel.setBounds(360, 10, 90, 30);

        btncon.setText("Add");
        btncon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconActionPerformed(evt);
            }
        });
        jPanel3.add(btncon);
        btncon.setBounds(210, 10, 90, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 320, 700, 50);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-715)/2, (screenSize.height-410)/2, 715, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("E:/Pic Memo/kiran pp photo");
        chooser.showOpenDialog(null);

        File file = chooser.getSelectedFile();
        if (file != null) {
            photoPath = file.getPath();
            ImageIcon icon = new ImageIcon(photoPath);

            photo.setIcon(icon);
        } else {
            JOptionPane.showMessageDialog(this, "NO Photo Selected.");
        }
}//GEN-LAST:event_uploadActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btncancelActionPerformed

    private void btnconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconActionPerformed
        // TODO add your handling code here:

        if ((fname.getText()).trim().equals("") || (lname.getText()).trim().equals("") || (contact.getText()).trim().equals("")
                || cbbdy.getSelectedIndex() == 0 || cbbdm.getSelectedIndex() == 0 || cbbdd.getSelectedIndex() == 0
                || cbady.getSelectedIndex() == 0 || cbadm.getSelectedIndex() == 0 || cbadd.getSelectedIndex() == 0
                || gender.getSelectedIndex() == 0 || (address.getText()).trim().equals("") || qua.getSelectedIndex() == 0
                || photoPath == null) {
            JOptionPane.showMessageDialog(this, "Please provide the full requirement", "Warning!!!!!!!", JOptionPane.PLAIN_MESSAGE);
        } else if (Pattern.matches(phoneNum, contact.getText().trim()) == false) {
            JOptionPane.showMessageDialog(this, "Not a Valid Number!!\nPlease try with 984******* or 980******* or 981*******");
        } else {
            String Sname = nameFormat();
            String bm = String.valueOf(cbbdm.getSelectedIndex()), am = String.valueOf(cbadm.getSelectedIndex());
            if (bm.length() < 2) {
                bm = "0" + bm;
            }
            if (am.length() < 2) {
                am = "0" + am;
            }
            String[] values = {Sname, (cbbdy.getSelectedItem() + "-" + bm + "-" + cbbdd.getSelectedItem()),
                address.getText(), contact.getText(), ((String) gender.getSelectedItem()), ((String) qua.getSelectedItem()),
                (cbady.getSelectedItem() + "-" + am + "-" + cbadd.getSelectedItem()), photoPath};
            insertNew(values);
        }
}//GEN-LAST:event_btnconActionPerformed

    private void cbbdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbdmActionPerformed
        // TODO add your handling code here:
        Object cb = evt.getSource();
        int i = ((JComboBox) evt.getSource()).getSelectedIndex();
        switch (i) {
            case 1:
                setDay(cb, 31);
                break;
            case 2:
                setDay(cb, 29);
                break;
            case 3:
                setDay(cb, 31);
                break;
            case 4:
                setDay(cb, 30);
                break;
            case 5:
                setDay(cb, 31);
                break;
            case 6:
                setDay(cb, 30);
                break;
            case 7:
                setDay(cb, 31);
                break;
            case 8:
                setDay(cb, 31);
                break;
            case 9:
                setDay(cb, 30);
                break;
            case 10:
                setDay(cb, 31);
                break;
            case 11:
                setDay(cb, 30);
                break;
            case 12:
                setDay(cb, 31);
                break;

        }
    }//GEN-LAST:event_cbbdmActionPerformed

    private String nameFormat() {

        String Sname = "";

        if ((mname.getText().trim()).equalsIgnoreCase("")) {
            Sname = fname.getText().trim() + " " + lname.getText().trim();
        } else {
            Sname = fname.getText().trim() + " " + mname.getText().trim() + " " + lname.getText().trim();
        }
        return Sname;
    }

    private void cbadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbadmActionPerformed
        // TODO add your handling code here:
        Object cb = evt.getSource();
        int i = ((JComboBox) evt.getSource()).getSelectedIndex();
        switch (i) {
            case 1:
                setDay(cb, 31);
                break;
            case 2:
                setDay(cb, 29);
                break;
            case 3:
                setDay(cb, 31);
                break;
            case 4:
                setDay(cb, 30);
                break;
            case 5:
                setDay(cb, 31);
                break;
            case 6:
                setDay(cb, 30);
                break;
            case 7:
                setDay(cb, 31);
                break;
            case 8:
                setDay(cb, 31);
                break;
            case 9:
                setDay(cb, 30);
                break;
            case 10:
                setDay(cb, 31);
                break;
            case 11:
                setDay(cb, 30);
                break;
            case 12:
                setDay(cb, 31);
                break;

        }
    }//GEN-LAST:event_cbadmActionPerformed

    protected void setDay(Object obj, int d) {
        if (obj.equals(cbadm)) {
            for (int i = 0; i <= d; i++) {
                if (i == 0) {
                    cbadd.addItem("Sel");
                } else if (i < 10) {
                    cbadd.addItem(String.valueOf("0" + i));
                } else {
                    cbadd.addItem(String.valueOf(i));
                }
            }
        } else {
            for (int i = 0; i <= d; i++) {
                if (i == 0) {
                    cbbdd.addItem("Sel");
                } else if (i < 10) {
                    cbbdd.addItem(String.valueOf("0" + i));
                } else {
                    cbbdd.addItem(String.valueOf(i));
                }
            }
        }
    }

    private void insertNew(String[] values) {

        Teacher t = new Teacher();
        query = "INSERT INTO teacher_info (id,teacherId,name,dob,address,contact,gender,qfc,salary,empd,photo)"
                                            + "VALUES (null,?,?,?,?,?,?,?,(SELECT salary FROM tsalaryamount WHERE qfc = '" + values[5] + "'),?,?)";
        boolean report = t.addNewTeacher(query, values);
        t.Close();
        if(report){
            JOptionPane.showMessageDialog(this, "Teacher Record Added Succesfully");
        }
        else{
            JOptionPane.showMessageDialog(this, "Please Try Again. Process Failed");
        }
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new NewTeacherF().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncon;
    private javax.swing.JComboBox cbadd;
    private javax.swing.JComboBox cbadm;
    private javax.swing.JComboBox cbady;
    private javax.swing.JComboBox cbbdd;
    private javax.swing.JComboBox cbbdm;
    private javax.swing.JComboBox cbbdy;
    private javax.swing.JFormattedTextField contact;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JLabel photo;
    private javax.swing.JComboBox qua;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
