package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResultGrade.java
 *
 * Created on Aug 15, 2012, 8:29:15 PM
 */
/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.BorderFactory.*;
import java.sql.*;

public class ResultGrade extends javax.swing.JFrame {

    private Connection con = null;
    private ResultSet rs = null;
    private String driver = "com.mysql.jdbc.Driver";
    private String urlCon = "jdbc:mysql://localhost:3306/System";
    private String query = null;
    private Statement stm = null;
    private PreparedStatement pst = null;
    String title = "";

    /** Creates new form ResultGrade */
    public ResultGrade() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        cmbterm = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmbgrade2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setText("Terms:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 80, 50, 30);

        cmbterm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "First", "Second", "Final" }));
        getContentPane().add(cmbterm);
        cmbterm.setBounds(130, 75, 140, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/result1.png"))); // NOI18N
        jLabel1.setText("Result");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 553, 60);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 160, 90, 30);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 160, 90, 30);

        cmbgrade2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "X9", "X10" }));
        getContentPane().add(cmbgrade2);
        cmbgrade2.setBounds(400, 80, 90, 30);

        jLabel5.setText("Grade:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 90, 50, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-569)/2, (screenSize.height-250)/2, 569, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (cmbterm.getSelectedIndex() != 0) {
            int term = cmbterm.getSelectedIndex();
            String grade = (String) cmbgrade2.getSelectedItem();

            if (!grade.equalsIgnoreCase("select") && term != 0) {
                CommonTabulateData cd = new CommonTabulateData();
                query = "SELECT exam.name, exam.studentId, exam.roll, exam.report, exam.contact FROM exam,examterm "
                        + "WHERE exam.id = examterm.id AND examterm.grade = '" + grade + "' AND examterm.term = '" + term + "' AND date_format(date,'%y') = date_format(now(),'%y')";
                if (cd.dataValidCheck(query)) {
                    title = "RESULTS OF GRADE "+grade+" OF TERM "+ term;
                    new TabulateData(title,query).setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No data found.\nNo result records has been uploaded. thank you");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please Provide all Info");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error in Connection");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new ResultGrade().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbgrade2;
    private javax.swing.JComboBox cmbterm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
