package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StaffInfoF.java
 *
 * Created on Jan 22, 2012, 10:12:39 PM
 */
/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import java.sql.*;
import java.awt.*;
import java.awt.event.*;

public class StaffInfoF extends javax.swing.JFrame {

    private String staffId = "", post = "";
    private String query = null;

    /** Creates new form StaffInfoF */
    public StaffInfoF(ResultSet rs) {


        initComponents();
        fname.setEnabled(false);
        lname.setEnabled(false);
        mname.setEnabled(false);
        cmbpost.setEnabled(false);
        staffid.setEnabled(false);
        gender.setEnabled(false);
        address.setEnabled(false);
        txtsalary.setEnabled(false);
        contact.setEnabled(false);
        save.setEnabled(false);
        connectionToDatabase(rs);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        staffid = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        txtsalary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        cmbpost = new javax.swing.JComboBox();
        id1 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtempd = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staffInfo.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Salary/Month:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(340, 180, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("First Name:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 30, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("M. Name:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(260, 30, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Last Name:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(470, 30, 70, 30);

        fname.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(fname);
        fname.setBounds(110, 30, 110, 30);

        staffid.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(staffid);
        staffid.setBounds(340, 80, 100, 30);

        lname.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(lname);
        lname.setBounds(560, 30, 110, 30);

        txtsalary.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtsalary.setText("Rs. ");
        jPanel2.add(txtsalary);
        txtsalary.setBounds(440, 180, 130, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Post:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 80, 50, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Address:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 130, 60, 30);

        lblid.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblid.setForeground(new java.awt.Color(51, 51, 255));
        lblid.setText("Gender:");
        jPanel2.add(lblid);
        lblid.setBounds(470, 80, 60, 30);

        address.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(address);
        address.setBounds(110, 130, 200, 30);

        contact.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(contact);
        contact.setBounds(440, 130, 130, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Contact No:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(340, 130, 80, 30);

        mname.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(mname);
        mname.setBounds(340, 30, 100, 30);

        cmbpost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PRINCIPLE", "VICE-PRINCIPLE", "ACCOUNTANT", "ADMINISTRATIVE", "DI", "GUARD", "COUNSELLER", "CLERK", "CLEANER", "GARDENDER", "COOK" }));
        jPanel2.add(cmbpost);
        cmbpost.setBounds(110, 80, 110, 30);

        id1.setFont(new java.awt.Font("Tahoma", 0, 14));
        id1.setForeground(new java.awt.Color(51, 51, 255));
        id1.setText("Staff ID:");
        jPanel2.add(id1);
        id1.setBounds(260, 80, 60, 30);

        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel2.add(gender);
        gender.setBounds(560, 80, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Address:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 180, 60, 30);

        txtempd.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel2.add(txtempd);
        txtempd.setBounds(110, 180, 150, 30);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(699, 50));
        jPanel3.setLayout(null);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 14));
        cancel.setText("OK");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel);
        cancel.setBounds(470, 10, 90, 30);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(110, 9, 90, 30);

        edit.setFont(new java.awt.Font("Tahoma", 1, 14));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit);
        edit.setBounds(300, 10, 90, 30);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-715)/2, (screenSize.height-375)/2, 715, 375);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //        new Staff_Sec().setVisible(true);
}//GEN-LAST:event_cancelActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        fname.setEnabled(true);
        lname.setEnabled(true);
        mname.setEnabled(true);
        cmbpost.setEnabled(true);
        gender.setEnabled(true);
        address.setEnabled(true);
        contact.setEnabled(true);
        save.setEnabled(true);
}//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String name = "";
        if (mname.getText().trim().equalsIgnoreCase("")) {
            name = fname.getText().trim() + " " + lname.getText().trim();
        } else {
            name = fname.getText().trim() + " " + mname.getText().trim() + " " + lname.getText().trim();
        }
        String[] values = {name, gender.getSelectedItem().toString(), address.getText(),
            contact.getText(), cmbpost.getSelectedItem().toString(), txtempd.getText().trim()};
        query = "UPDATE staff_info SET "
                + "name = ?, "
                + "gender = ?, "
                + "address = ?, "
                + "contact = ?, "
                + "post = ? ,"
                + "salary = (SELECT salary FROM salaryamount WHERE post = '" + values[4] + "'), "
                + "empd = ?"
                + " WHERE staffId = ?";
        Staff st = new Staff();
        int report = st.updateStaffInfo(values, query, staffId);
        st.Close();
        if (report > 0) {
            JOptionPane.showMessageDialog(this, "Record Updated Successfully");
            this.dispose();
            new StaffSecF().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error in Updating");
        }

    }//GEN-LAST:event_saveActionPerformed

    private void connectionToDatabase(ResultSet rs) {
        try {
            int i, j, len1, len2;
            staffId = rs.getString("staffId");
            String s1 = null, s2 = null, s3 = null, s4 = null;
            String name = (rs.getString("name")).trim().toUpperCase();
            len1 = name.length();
            if (len1 > 0) {
                i = name.indexOf(" ");
                s1 = name.substring(0, i);
                s2 = (name.substring(i, len1)).trim();
                len2 = s2.length();
                j = s2.indexOf(" ");
                if (j > 0) {
                    s3 = s2.substring(0, j);
                    s4 = (s2.substring(j, len2)).trim();
                    fname.setText(s1);
                    mname.setText(s3);
                    lname.setText(s4);
                } else {
                    fname.setText(s1);
                    lname.setText(s2);
                }
            }
            //id = rs.getInt("id");
            txtempd.setText(rs.getDate("empd").toString());
            post = rs.getString("post");
            cmbpost.setSelectedItem(rs.getString("post"));
            staffid.setText(rs.getString("staffid"));
            gender.setSelectedItem(rs.getString("gender"));
            address.setText(rs.getString("address"));
            contact.setText(rs.getString("contact"));
            txtsalary.setText(String.valueOf(rs.getFloat("salary")));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inside StaffInfo: " + e.getMessage(), "Notice", JOptionPane.PLAIN_MESSAGE);
        } finally {
            try{
            rs.close();
            }
            catch(Exception e){}
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StaffInfoF().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox cmbpost;
    private javax.swing.JTextField contact;
    private javax.swing.JButton edit;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox gender;
    private javax.swing.JLabel id1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JButton save;
    private javax.swing.JTextField staffid;
    private javax.swing.JTextField txtempd;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
