package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StaffSalary.java
 *
 * Created on Sep 9, 2011, 7:19:42 PM
 */

/**
 *
 * @author kiranroma
 */
public class StaffSalary extends javax.swing.JPanel {

    /** Creates new form StaffSalary */
    public StaffSalary() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staffsalary_1.png"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Post:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 140, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("S.No:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 20, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("First Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 80, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("M. Name:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 80, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Last Name:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 80, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Salary/Month:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 140, 90, 30);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(50, 20, 70, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(90, 80, 110, 30);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(290, 80, 100, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(480, 80, 110, 30);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jTextField5.setText("Rs. ");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(320, 140, 110, 30);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jPanel1.add(jTextField7);
        jTextField7.setBounds(90, 140, 110, 30);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(597, 40));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Not Paid");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 10, 180, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("OK");
        jPanel2.add(jButton1);
        jButton1.setBounds(410, 10, 60, 25);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
