package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubDel.java
 *
 * Created on Sep 18, 2011, 4:23:14 PM
 */

/**
 *
 * @author kiranroma
 */
import javax.swing.*;
import java.sql.*;

public class SubDel extends javax.swing.JFrame {

   private Connection con = null;
   private PreparedStatement pst = null;
   private String driver = "com.mysql.jdbc.Driver";
   private String conUrl = "jdbc:mysql://localhost:3306/system";
   private String query = null;
   private ResultSet rs = null;

    ///////////////////////// data to search for database******************

    private String[] cs;
    private int scount ;
    private String tea_name;
    private String tea_id;
    /** Creates new form SubDel */
    public SubDel(String teacher, String teacherid, String[] csub, int count) {
        cs = csub;
        scount = count;
        tea_name = teacher;
        tea_id = teacherid;
        initComponents();
        tid.setText(teacherid);
        name.setText(teacher);
        if(scount != 3 && scount < 3){

            class1.setText(cs[0]);
            chk1.setText(cs[1]);
            
            class2.setText("No Class");
            class2.setEnabled(false);
            chk2.setEnabled(false);
        }
        else if(scount == 3){

            class1.setText(cs[0]);
            chk1.setText(cs[1]);
            //chk2.setEnabled(false);
            class2.setText(cs[2]);
            chk2.setText(cs[3]);
            //class2.setEnabled(false);

        }

        for(String s:cs){
        System.out.println(s);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        class1 = new javax.swing.JLabel();
        class2 = new javax.swing.JLabel();
        chk2 = new javax.swing.JCheckBox();
        chk1 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Remove Subject");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(null);

        add.setText("Delete");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(120, 240, 80, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Subject To Delete:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 51))); // NOI18N
        jPanel3.setLayout(null);

        class1.setFont(new java.awt.Font("Tahoma", 0, 14));
        class1.setForeground(new java.awt.Color(0, 102, 255));
        class1.setText("c1");
        jPanel3.add(class1);
        class1.setBounds(10, 30, 60, 30);

        class2.setFont(new java.awt.Font("Tahoma", 0, 14));
        class2.setForeground(new java.awt.Color(0, 102, 255));
        class2.setText("c2");
        jPanel3.add(class2);
        class2.setBounds(10, 70, 60, 30);

        chk2.setText("check2");
        jPanel3.add(chk2);
        chk2.setBounds(120, 70, 90, 30);

        chk1.setText("check1");
        jPanel3.add(chk1);
        chk1.setBounds(120, 30, 90, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 120, 220, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 51))); // NOI18N
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Name:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 20, 50, 20);

        name.setFont(new java.awt.Font("Tahoma", 0, 12));
        name.setForeground(new java.awt.Color(255, 0, 0));
        name.setText("name");
        jPanel4.add(name);
        name.setBounds(100, 20, 110, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Teacher ID:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 60, 80, 20);

        tid.setFont(new java.awt.Font("Tahoma", 0, 12));
        tid.setForeground(new java.awt.Color(255, 0, 0));
        tid.setText("id");
        jPanel4.add(tid);
        tid.setBounds(100, 60, 110, 20);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 10, 220, 100);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);
        cancel.setBounds(20, 240, 80, 30);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-237)/2, (screenSize.height-338)/2, 237, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(scount != 3 && scount < 3){
            if(chk1.isSelected()){
                deleteSub(0,1);
            }
            else {
                JOptionPane.showMessageDialog(this, "Please Check the box","Notice",JOptionPane.PLAIN_MESSAGE);
            }
        }
        else{
            if(!chk1.isSelected() && !chk2.isSelected()){
                JOptionPane.showMessageDialog(this, "Please Check the box","Notice",JOptionPane.PLAIN_MESSAGE);
            }
            else if(chk1.isSelected()){
                deleteSub(0,1);
            }
            else if(chk2.isSelected()){
                deleteSub(2,3);
            }
            else if (chk1.isSelected() && chk2.isSelected()){
                deleteSub(0,3);
            }
        }
        

    }//GEN-LAST:event_addActionPerformed

    private void deleteSub(int f, int l){
        int result;
        dbConnect db = new dbConnect();
        con = db.Connect();
        if(con != null){
        try{
//            Class.forName(driver);
//            con = DriverManager.getConnection(conUrl,"root","");
            query = "DELETE FROM teacher_sub WHERE teacherId = ? "
                   // + "AND teacher = ?"
                    + " AND class = ?"
                    + " AND subject = ?";
            pst = con.prepareStatement(query);
            if( (l-f) == 1){
                pst.setString(1,tea_id);
               // pst.setString(2,tea_name);
                pst.setString(2,cs[f]);
                pst.setString(3,cs[l]);
                result = pst.executeUpdate();
                if(result > 0){
                    JOptionPane.showMessageDialog(this, "Subject "+ cs[l] + " of class "+ cs[f] +" by "+tea_name+" "
                            + " has been deleted...", "Notice!!", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                    new NewTeaSub().setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(this," Error Sql(single delete)", "Notice!!", JOptionPane.PLAIN_MESSAGE);
                }
            }
            else if( (l-f) != 1 && (l-f) > 1){
                pst.setString(1,tea_id);
                //pst.setString(2,tea_name);
                pst.setString(2,cs[f]);
                pst.setString(3,cs[f+1]);
                int result1 = pst.executeUpdate();

                pst.setString(1,tea_id);
                //pst.setString(2,tea_name);
                pst.setString(2,cs[f+2]);
                pst.setString(3,cs[l]);
                result = pst.executeUpdate();
                if(result1 > 0 && result >0)
                {
                    JOptionPane.showMessageDialog(this, "Subject "+ cs[f+1] + "and "+cs[l]+"of class "+ cs[f] +" and "+cs[f+2]+" by "+tea_name+" has been deleted...",
                            "Notice!!", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                    new NewTeaSub().setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this," Error Sql(single delete)", "Notice!!", JOptionPane.PLAIN_MESSAGE);
                }
            }
        }
        catch(Exception e){

        }
        finally{
        try{
            if(con != null){
                con.close();
            }
        }
        catch(Exception e){}
        }
        }
 else{
        JOptionPane.showMessageDialog(this," Error in Connection");
 }
    }

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new NewTeaSub().setVisible(true);
}//GEN-LAST:event_cancelActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//         final String[] name = {"kiran","ram"};
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SubDel("teacher","1234",name,1).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JLabel class1;
    private javax.swing.JLabel class2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel tid;
    // End of variables declaration//GEN-END:variables

}
