package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Teacher_Sub.java
 *
 * Created on Sep 17, 2011, 11:10:58 PM
 */
import javax.swing.*;
import java.awt.*;
import java.sql.*;

/**
 *
 * @author kiranroma
 */
public class Teacher_Sub extends javax.swing.JFrame {
//
//    private JLabel lblc1;
//private JLabel lblc2;
//private JComboBox cmbs1;
//private JComboBox cmbs2;

    /** Creates new form SubjectAdd */
//// to store tha data ****************
    private String cl1;
    private String cl2;
    private String teacher;
    private String qua;
    private String tid;
    private float salary;
    private String[] qualif = {"BACHELOR", "GENERAL", "MASTER", "PH.D", "SLC"};
//private static String[] qualif = {"master","undergraduate","bachelor","ph.d","slc"};
    private float[] tsalary = {21000f, 18000f, 25000f, 30000f, 14000f};
//////****************************
//private String photoPath = null;
    private Connection con = null;
    private PreparedStatement pst = null;
    private String driver = "com.mysql.jdbc.Driver";
    private String conUrl = "jdbc:mysql://localhost:3306/system";
    private String query = null;

    /** Creates new form Teacher_Sub */
    public Teacher_Sub(String c1, String c2, String name, String qfc, String id) {
        for (String g : qualif) {
            System.out.println(g);
        }
        cl1 = c1;
        cl2 = c2;
        teacher = name;
        qua = qfc;
        tid = id;
//        tname1.setText(name);
//        quali1.setText(qfc);
//        teacherid1.setText(id);

        initComponents();
        if (!c2.equalsIgnoreCase("")) {
            class1.setText("Class " + c1);
            class2.setText("Class " + c2);
        } else {
            class1.setText("Class " + c1);
            class2.setText("No Class");
            cmbs2.setEnabled(false);
        }

//        if(c1.equalsIgnoreCase("") || c2.equalsIgnoreCase("")){
//            if(!c2.equalsIgnoreCase("")){
//                lblc2 = new JLabel();
//                lblc2.setFont(new Font("Tahoma", 0, 14));
//                lblc2.setText("Subject for Class "+c2+":");
//                jPanel1.add(lblc2);
//                lblc2.setBounds(10, 110,125, 20);
//
//                cmbs2 = new JComboBox();
//                cmbs2.setModel(new DefaultComboBoxModel(new String[] { "SELECT", "MATH", "SCIENCE", "NEPALI", "ACCOUNT", "SOCIAL STD.", "HEALTH", "ENGLISH"}));
//                jPanel1.add(cmbs2);
//                cmbs2.setBounds(140, 110, 95, 25);
//            }
//            else{
//                lblc1 = new JLabel();
//                lblc1.setFont(new Font("Tahoma", 0, 14));
//                lblc1.setText("Subject for Class "+c1+":");
//                jPanel1.add(lblc1);
//                lblc1.setBounds(10, 110,127, 20);
//
//                cmbs1 = new JComboBox();
//                cmbs1.setModel(new DefaultComboBoxModel(new String[] { "SELECT", "MATH", "SCIENCE", "NEPALI", "ACCOUNT", "SOCIAL STD.", "HEALTH", "ENGLISH"}));
//                jPanel1.add(cmbs1);
//                cmbs1.setBounds(140, 110, 95, 25);
//            }
//
//        }
//        else{
//                lblc1 = new JLabel();
//                lblc1.setFont(new Font("Tahoma", 0, 14));
//                lblc1.setText("Subject for Class "+c1);
//                jPanel1.add(lblc1);
//                lblc1.setBounds(10, 110,125, 20);
//
//                cmbs2 = new JComboBox();
//                cmbs2.setModel(new DefaultComboBoxModel(new String[] { "SELECT", "MATH", "SCIENCE", "NEPALI", "ACCOUNT", "SOCIAL STD.", "HEALTH", "ENGLISH"}));
//                jPanel1.add(cmbs2);
//                cmbs2.setBounds(140, 110, 95, 25);
//
//                lblc2 = new JLabel();
//                lblc2.setFont(new Font("Tahoma", 0, 14));
//                lblc2.setText("Subject for Class "+c2);
//                jPanel1.add(lblc2);
//                lblc2.setBounds(10, 140,125, 20);
//
//                cmbs2 = new JComboBox();
//                cmbs2.setModel(new DefaultComboBoxModel(new String[] { "SELECT", "MATH", "SCIENCE", "NEPALI", "ACCOUNT", "SOCIAL STD.", "HEALTH", "ENGLISH"}));
//                jPanel1.add(cmbs2);
//                cmbs2.setBounds(140, 140, 95, 25);
//        }
        tname1.setText(name);
        quali1.setText(qfc);
        teacherid1.setText(id);
        salary = getSalary(qua);
    }

    private float getSalary(String q) {
        int i = java.util.Arrays.binarySearch(qualif, q);
        System.out.println("inside getSalary " + i);
        return (tsalary[i]);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        class1 = new javax.swing.JLabel();
        class2 = new javax.swing.JLabel();
        cmbs2 = new javax.swing.JComboBox();
        cmbs1 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tname1 = new javax.swing.JLabel();
        quali1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        teacherid1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add1 = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Assign Subject");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(null);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(120, 240, 90, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Select Subject:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 51))); // NOI18N
        jPanel3.setLayout(null);

        class1.setFont(new java.awt.Font("Tahoma", 0, 14));
        class1.setForeground(new java.awt.Color(0, 102, 255));
        jPanel3.add(class1);
        class1.setBounds(10, 30, 80, 20);

        class2.setFont(new java.awt.Font("Tahoma", 0, 14));
        class2.setForeground(new java.awt.Color(0, 102, 255));
        jPanel3.add(class2);
        class2.setBounds(10, 60, 80, 20);

        cmbs2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "MATH", "SCIENCE", "NEPALI", "ACCOUNT", "SOCIAL STD.", "HEALTH", "ENGLISH" }));
        jPanel3.add(cmbs2);
        cmbs2.setBounds(100, 60, 110, 20);

        cmbs1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "MATH", "SCIENCE", "NEPALI", "ACCOUNT", "SOCIAL STD.", "HEALTH", "ENGLISH" }));
        cmbs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbs1ActionPerformed(evt);
            }
        });
        jPanel3.add(cmbs1);
        cmbs1.setBounds(100, 30, 110, 20);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 130, 220, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 51))); // NOI18N
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Name:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 20, 50, 20);

        tname1.setFont(new java.awt.Font("Tahoma", 0, 12));
        tname1.setForeground(new java.awt.Color(255, 0, 0));
        tname1.setText("name");
        jPanel4.add(tname1);
        tname1.setBounds(100, 20, 110, 20);

        quali1.setFont(new java.awt.Font("Tahoma", 0, 12));
        quali1.setForeground(new java.awt.Color(255, 0, 0));
        quali1.setText("id");
        jPanel4.add(quali1);
        quali1.setBounds(100, 80, 110, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Teacher ID:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(10, 50, 80, 20);

        teacherid1.setFont(new java.awt.Font("Tahoma", 0, 12));
        teacherid1.setForeground(new java.awt.Color(255, 0, 0));
        teacherid1.setText("id");
        jPanel4.add(teacherid1);
        teacherid1.setBounds(100, 50, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("Qualification:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 80, 80, 20);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 10, 220, 110);

        add1.setText("Cancel");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel2.add(add1);
        add1.setBounds(10, 240, 90, 30);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-237)/2, (screenSize.height-338)/2, 237, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String sub1 = null, sub2 = null;
        int i, j;
        if (!cl2.equalsIgnoreCase("")) {

            if (cmbs1.getSelectedIndex() > 0 || cmbs2.getSelectedIndex() > 0) {
                sub1 = ((String) cmbs1.getSelectedItem()).toUpperCase();
                sub2 = ((String) cmbs2.getSelectedItem()).toUpperCase();
                insertTeacherSub(sub1, sub2);
            } else {
                JOptionPane.showMessageDialog(this, "Please select both subject", "Warning!!!", JOptionPane.PLAIN_MESSAGE);
            }

        } else {
            if (cmbs1.getSelectedIndex() > 0) {
                sub1 = ((String) cmbs1.getSelectedItem()).toUpperCase();
                insertTeacherSub(sub1, "");
            } else {
                JOptionPane.showMessageDialog(this, "You forget to select the subject", "Warning!!!", JOptionPane.PLAIN_MESSAGE);
            }
        }


    }//GEN-LAST:event_addActionPerformed

    private void cmbs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbs1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new NewTeaSub().setVisible(true);
    }//GEN-LAST:event_add1ActionPerformed

    private void insertTeacherSub(String sub1, String sub2) {
        int result = 0;
        int result1 = 0;
        dbConnect db = new dbConnect();
        con = db.Connect();
        if (con != null) {
            try {
//        Class.forName(driver);
//        con = DriverManager.getConnection(conUrl,"root","");
                query = "INSERT INTO teacher_sub (id,teacherId,class,subject,salary) VALUES (null,?,?,?,?)";
                pst = con.prepareStatement(query);

                if (!cl2.equalsIgnoreCase("")) {
                    pst.setString(1, tid);
//        pst.setString(2, qua);
                    pst.setString(2, cl1);
                    pst.setString(3, sub1);
                    //pst.setString(5, teacher);
                    pst.setFloat(4, salary);
                    result1 = pst.executeUpdate();
                    if (result1 > 0) {
                        pst.setString(1, tid);
//        pst.setString(2, qua);
                        pst.setString(2, cl2);
                        pst.setString(3, sub2);
                        //pst.setString(5, teacher);
                        pst.setFloat(4, salary);
                        result = pst.executeUpdate();

                        //result = pst.executeUpdate();
                        if (result > 0) {

                            JOptionPane.showMessageDialog(this, "Inserted Successfully (two sub)", "Notice!!!", JOptionPane.PLAIN_MESSAGE);
                            this.dispose();
                            new NewTeaSub().setVisible(true);

                        } else {
                            JOptionPane.showMessageDialog(this, "Error in query (two sub)", "Warning!!!", JOptionPane.PLAIN_MESSAGE);
                            this.dispose();
                            new NewTeaSub().setVisible(true);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Error in first query", "Notice!!!", JOptionPane.PLAIN_MESSAGE);
                        this.dispose();
                        new NewTeaSub().setVisible(true);
                        //this.dispose();
                    }

//        //////////////////////// second one......................
//
//        pst.setString(1, tid);
////        pst.setString(2, qua);
//        pst.setString(2, cl2);
//        pst.setString(3, sub2);
//        //pst.setString(5, teacher);
//        pst.setFloat(4, salary);
//        result = pst.executeUpdate();
//
//        result = pst.executeUpdate();
//        if(result < 0){
//            JOptionPane.showMessageDialog(this, "Error in query (two sub)", "Warning!!!", JOptionPane.PLAIN_MESSAGE);
//            }
//        else {
//                JOptionPane.showMessageDialog(this, "Inserted Successfully (two sub)", "Notice!!!", JOptionPane.PLAIN_MESSAGE);
//                this.dispose();
//                new NewTeaSub().setVisible(true);
//            }
                } else {
//        query = "INSERT INTO (id,teacherId,qfc,toc,subject,teacher,salary) VALUES (null,?,?,?,?,?,?)";
//        pst = con.prepareStatement(query);

                    pst.setString(1, tid);
                    //pst.setString(2, qua);
                    pst.setString(2, cl1);
                    pst.setString(3, sub1);
                    // pst.setString(5, teacher);
                    pst.setFloat(4, salary);
                    result = pst.executeUpdate();
                    if (result < 0) {
                        JOptionPane.showMessageDialog(this, "Error in query (single sub)", "Warning!!!", JOptionPane.PLAIN_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Inserted Successfully (single sub)", "Notice!!!", JOptionPane.PLAIN_MESSAGE);
                        this.dispose();
                        new NewTeaSub().setVisible(true);
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error in Teacher_Sub " + e.getMessage(), "Notice!!!", JOptionPane.PLAIN_MESSAGE);
            } finally {
                try {
                    if (con != null) {
                        con.close();
                    }
                } catch (Exception e) {
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error in Connection");
        }
    }
    // }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                 //System.out.println(java.util.Arrays.binarySearch(qualif, "ph.d"));
//                new Teacher_Sub("kk","kk","name","MASTER","dd").setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JLabel class1;
    private javax.swing.JLabel class2;
    private javax.swing.JComboBox cmbs1;
    private javax.swing.JComboBox cmbs2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel quali1;
    private javax.swing.JLabel teacherid1;
    private javax.swing.JLabel tname1;
    // End of variables declaration//GEN-END:variables
}
