package newpackage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TeacherSecF.java
 *
 * Created on Jan 24, 2012, 8:28:58 AM
 */
/**
 *
 * @author kiranroma
 */
import java.sql.*;
import javax.swing.*;

public class TeacherSecF extends javax.swing.JFrame {

    private String query = null;

    /** Creates new form TeacherSecF */
    public TeacherSecF() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        info = new javax.swing.JButton();
        salary = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TEACHERSEC.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 63);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Enter Required Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(590, 60));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Teacher ID:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(370, 30, 80, 20);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPanel2.add(txtid);
        txtid.setBounds(460, 20, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Name:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 30, 50, 20);

        txtname.setFont(new java.awt.Font("Tahoma", 0, 12));
        jPanel2.add(txtname);
        txtname.setBounds(110, 20, 200, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 600, 70);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 51))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(590, 60));
        jPanel3.setLayout(null);

        info.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        info.setForeground(new java.awt.Color(51, 0, 204));
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        info.setText("Info");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        jPanel3.add(info);
        info.setBounds(50, 20, 140, 30);

        salary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salary.setForeground(new java.awt.Color(51, 0, 204));
        salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1.png"))); // NOI18N
        salary.setText("Salary");
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel3.add(salary);
        salary.setBounds(220, 20, 140, 30);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(510, 20, 80, 30);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(380, 20, 110, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 140, 600, 60);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-616)/2, (screenSize.height-246)/2, 616, 246);
    }// </editor-fold>//GEN-END:initComponents

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        String sname = (txtname.getText()).trim();
        String teacherId = (txtid.getText()).trim();

        if (!sname.equalsIgnoreCase("") && !teacherId.equalsIgnoreCase("")) {
            String stname = getName(sname);
            if (!stname.equals("")) {
                query = "SELECT * FROM teacher_info WHERE name = '"+stname+"'"
                                + "AND teacherId = '"+teacherId+"'";
                Teacher t = new Teacher();
                ResultSet rs = t.getTeacherInfo(query);
                if(rs != null){
                    new TeacherInfoF(rs).setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Data Not Found or Error.");
                    txtname.setText("");
                    txtid.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Enter the full name !!!!", "Notice", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill up the both field", "Notice", JOptionPane.PLAIN_MESSAGE);
        }
}//GEN-LAST:event_infoActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
        String sname = (txtname.getText()).trim();
        String teacherId = (txtid.getText()).trim();

        if (!sname.equalsIgnoreCase("") && !teacherId.equalsIgnoreCase("")) {
            String stname = getName(sname);
            if (!stname.equals("")) {
                query = "SELECT qfc FROM teacher_info WHERE teacherId = '"+teacherId+"'";
                Teacher t = new Teacher();
                String qua = t.getQualification(query); // also can be used for validation
                t.Close();
                if(qua.equalsIgnoreCase("")){
                    JOptionPane.showMessageDialog(this, "No Record exist of the given info. Sorry");
                }
                else{
                    new SalaryOptionF(stname,teacherId,qua,2).setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Enter the full name !!!!", "Notice", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill up the both field", "Notice", JOptionPane.PLAIN_MESSAGE);
        }
}//GEN-LAST:event_salaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtname.setText("");
        txtid.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private String getName(String name) {
        int len1 = 0, len2 = 0, i = 0, j = 0;
        String sname = "", s1 = "", s2 = "", s3 = "", s4 = "";


        i = name.indexOf(" ");
        if (i > 0) {
            len1 = name.length();
            s1 = name.substring(0, i);
            sname += s1 + " ";
            s2 = (name.substring(i, len1)).trim();

            j = s2.indexOf(" ");
            if (j > 0) {
                len2 = s2.length();
                s3 = s2.substring(0, j);
                sname += s3 + " ";
                s4 = (s2.substring(j, len2)).trim();
                sname += s4 + " ";
            } else {
                sname += s2;
            }
        }

        return (sname);
    }



    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new TeacherSecF().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton salary;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
